//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportwearStore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clothes()
        {
            this.Bucket = new HashSet<Bucket>();
            this.ProductPhoto = new HashSet<ProductPhoto>();
            this.Category = new HashSet<Category>();
            this.Size = new HashSet<Size>();
            this.Clothes1 = new HashSet<Clothes>();
            this.Clothes2 = new HashSet<Clothes>();
        }
    
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public string Articul { get; set; }
        public string Description { get; set; }
        public int IDColor { get; set; }
        public int IDCollection { get; set; }
        public int IDCountry { get; set; }
        public int IDSeason { get; set; }
        public int IDMaterial { get; set; }
        public int IDStyle { get; set; }
        public string MainPhoto { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bucket> Bucket { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Color Color { get; set; }
        public virtual ManufactureCountry ManufactureCountry { get; set; }
        public virtual Material Material { get; set; }
        public virtual Season Season { get; set; }
        public virtual Style Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhoto> ProductPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothes> Clothes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothes> Clothes2 { get; set; }
    }
}
