//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportwearStore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionOfTheMaterial
    {
        public int IDMaterial { get; set; }
        public int IDComposition { get; set; }
        public decimal PercentContent { get; set; }
    
        public virtual Composition Composition { get; set; }
        public virtual Material Material { get; set; }
    }
}
