//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportwearStore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bucket = new HashSet<Bucket>();
            this.ProductColor = new HashSet<ProductColor>();
            this.Category = new HashSet<Category>();
            this.Size = new HashSet<Size>();
            this.Product1 = new HashSet<Product>();
            this.Product2 = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public string ArticleProduct { get; set; }
        public int IDCollection { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int IDMaterial { get; set; }
        public int IDStyle { get; set; }
        public int IDSeason { get; set; }
        public int IDManufacturerCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bucket> Bucket { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual ManufactureCountry ManufactureCountry { get; set; }
        public virtual Material Material { get; set; }
        public virtual Season Season { get; set; }
        public virtual Style Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductColor> ProductColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product2 { get; set; }
    }
}
